In [1]:
import os
os.chdir("..//src")
from Boundary import *
import numpy as np

In [2]:
cbd = CircleBoundary()
cbd.setCircle((0.5, 0.5), 0.1, 20)

In [3]:
cbd.setNodalPsi(1)
cbd.setLinearPsi(1)
cbd.setNodalSpace(0.01)

In [4]:
cbd.calSumPsiJLinearPart(0, 0)

40.8027421995162

In [5]:
cbd.calSumPsiILinearPart(0, 0)

0.4080274219951621

In [6]:
cbd.nodal_psi

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [7]:
cbd.linear_psi

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
cbd.nodal_space

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])

In [9]:
cbd.xy

array([[0.6       , 0.5       ],
       [0.59510565, 0.5309017 ],
       [0.5809017 , 0.55877853],
       [0.55877853, 0.5809017 ],
       [0.5309017 , 0.59510565],
       [0.5       , 0.6       ],
       [0.4690983 , 0.59510565],
       [0.44122147, 0.5809017 ],
       [0.4190983 , 0.55877853],
       [0.40489435, 0.5309017 ],
       [0.4       , 0.5       ],
       [0.40489435, 0.4690983 ],
       [0.4190983 , 0.44122147],
       [0.44122147, 0.4190983 ],
       [0.4690983 , 0.40489435],
       [0.5       , 0.4       ],
       [0.5309017 , 0.40489435],
       [0.55877853, 0.4190983 ],
       [0.5809017 , 0.44122147],
       [0.59510565, 0.4690983 ]])